name: programacionIA
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytest
  - pandas
  - scikit-learn
  - torchvision
  - torchaudio
  - cpuonly
  - opencv
  - jupyter
  - matplotlib
  - dlib
  - chromadb
